using UnityEngine;
using System.Collections.Generic;

public class AnimAsset  {
    public List<Setoffset> AttackQuyen;
    public List<Setoffset> AttackDao1;
    public List<Setoffset> AttackDao2;
    public List<Setoffset> AttackBong1;
    public List<Setoffset> AttackBong2;
    public List<Setoffset> AttackChuy1;
    public List<Setoffset> AttackChuy2;
    public List<Setoffset> DeadQuyen;
    public List<Setoffset> DeadDao;
    public List<Setoffset> DeadBong;
    public List<Setoffset> DeadChuy;
    public List<Setoffset> AttackPet1;
    public List<Setoffset> AttackPet2;
    public List<Setoffset> DeadPet;
    public List<Setoffset> HitPet;
    public List<Setoffset> AttackPetTieu;
    public List<Setoffset> PetRun;
    public List<Setoffset> PetWalk;
    public List<Setoffset> HitQuyen;
    public List<Setoffset> HitDao;
    public List<Setoffset> HitBong;
    public List<Setoffset> HitChuy;
    public List<Setoffset> Jump;
    public List<Setoffset> AttackTieu;
    public List<Setoffset> ChuongQuyen;
    public List<Setoffset> ChuongDao;
    public List<Setoffset> ChuongBong;
    public List<Setoffset> ChuongChuy;
    public List<Setoffset> PetStand;
    public List<Setoffset> RunQuyen;
    public List<Setoffset> RunDao;
    public List<Setoffset> RunBong;
    public List<Setoffset> RunChuy;
    public List<Setoffset> Stand1;
    public List<Setoffset> Stand2;
    public List<Setoffset> StandQuyen;
    public List<Setoffset> StandDao;
    public List<Setoffset> StandBong;
    public List<Setoffset> StandChuy;
    public List<Setoffset> WalkQuyen;
    public List<Setoffset> WalkDao;
    public List<Setoffset> WalkBong;
    public List<Setoffset> WalkChuy;
    public List<Setoffset> Thien;
}
